services:
  # Backend service
  backend:
    build: ./server
    container_name: backend-container
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "4000:4000"

  # Frontend service
  frontend:
    build: ./client
    container_name: frontend-container
    restart: always
    env_file:
      - ./client/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend
    
